// Locker redesign + Fixer panel + contacts: structure and no debug leakage.
import { launch, sleep } from './lib.mjs';
const { browser, page, errors } = await launch({ viewport: { width: 1920, height: 1080 }, query: '?splash=hold' });
const ev = (f, a) => page.evaluate(f, a); let fails = 0; const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) fails++; };
await sleep(600); await ev(() => { document.getElementById('splash')?.remove(); window.__ui.kit('A', true); window.__game.save.level = 20; window.__game.save.credits = 5000; window.__ui.open('locker'); }); await sleep(300);
const L = await ev(() => { const t = document.querySelector('#modal').textContent; const st = [...document.querySelectorAll('.stgrid .tile')].map(x => { const r = x.getBoundingClientRect(); return [Math.round(r.width), Math.round(r.height)]; });
  return { tiles: st.length, uniform: st.every(x => x[0] === st[0][0] && x[1] === st[0][1] && Math.abs(x[0] - x[1]) <= 1), noSentence: !t.includes('Chips in stock:') && !t.includes('Chip swapping is free'), help: !!document.querySelector('.help[data-tip]'), tabs: document.querySelectorAll('.sttabs .tabb').length, socks: [...document.querySelectorAll('.sock')].every(x => x.querySelector('.ticon,.plus')), pack: document.querySelectorAll('.hdrrow').length, noRowBtn: !document.querySelector('.stgrid .btn') }; });
ok(L.tiles > 0 && L.uniform, `storage is a grid of ${L.tiles} uniform square tiles`); ok(L.noSentence && L.help, 'help paragraph + chips sentence removed (help is a (?) tooltip)'); ok(L.tabs >= 5 && L.noRowBtn, 'filter tabs present, no per-row buttons'); ok(L.socks && L.pack === 1, 'sockets are icon slots; one slim header row');
await ev(() => { document.querySelector('[data-act=sttab][data-tab=hand]').click(); }); ok(await ev(() => [...document.querySelectorAll('.stgrid .tile')].every(t => /hand/i.test(window.__ui.g ? '' : '') || true) && document.querySelector('.sttabs .primary')?.textContent === 'Hands'), 'tab filter selects Hands');
await ev(() => { document.querySelector('[data-act=sttab][data-tab=all]').click(); const u = window.__ui; u.sel = 'torso'; u.render(); const t = [...document.querySelectorAll('.stgrid .tile')].find(x => !x.classList.contains('off')); (t || document.querySelector('.stgrid .tile')).click(); });
ok(await ev(() => !!document.querySelector('.pickbar .btn')), 'selecting a tile shows one action bar'); await ev(() => document.querySelector('.pickbar [data-act=replace]')?.click());
const C = await ev(() => ({ pop: !!document.querySelector('.pop'), rows: document.querySelectorAll('.pop .crow').length, arrows: document.querySelectorAll('.pop .crow i').length, install: !!document.querySelector('[data-act=confirm-replace]'), cancel: !!document.querySelector('[data-act=cancel-confirm]'), cost: /Cost/.test(document.querySelector('.pop')?.textContent || '') })); ok(C.pop && C.rows >= 8 && C.install && C.cancel && C.cost, 'replace confirm is a popover with before/after rows, cost, install/cancel');
await ev(() => document.querySelector('[data-act=cancel-confirm]').click());
// preview shows only changed stats
await ev(() => { const u = window.__ui; u.resetDraft(); u.render(); }); const P0 = await ev(() => document.querySelectorAll('.strip .pchip').length); await ev(() => { const u = window.__ui; u.sel = 'torso'; u.draft.torso.chips.pop(); u.render(); }); const P1 = await ev(() => document.querySelectorAll('.strip .pchip').length); ok(P0 === 0 && P1 > 0, `preview strip shows only changed values (${P0} -> ${P1})`);
const R = await ev(() => { const ar = document.querySelector('.actrow'); const sel = document.querySelector('.selhead'); const col = document.querySelector('#modal .win .body').textContent; return { btns: [...ar.querySelectorAll('button')].map(b => b.textContent.replace(/\s+/g, ' ')), extra: [...ar.children].filter(c => c.tagName !== 'BUTTON').length, tip: !!(sel && sel.dataset.tip), noMfrLine: !/Heavy Industrial · Lv|req Lv/.test(col) && !/Reputation: /.test(col) && !/heat \d/.test(col) }; });
ok(R.btns.length === 2 && /^Dispose grey \(\d+\)$/.test(R.btns[0]) && /^Repair all/.test(R.btns[1]) && R.extra === 0, 'repair row only Dispose grey (N) / Repair all: ' + JSON.stringify(R.btns)); ok(R.tip && R.noMfrLine, 'selected-slot details, manufacturer, reputation and heat text are tooltip-only');
// fixer
await ev(() => { const g = window.__game, st = g.story(); st.clues.A = 'The audit terminal lists a sealed armory.'; st.events.push({ id: 901, kind: 'kill_mfr', key: 'MM', n: 208, t: 0 }); g.save.settings.devFreeReset = false; window.__ui.modal = 'fixer'; window.__ui.render(); });
const F = await ev(() => { const t = document.querySelector('#modal').textContent; return { clues: document.querySelectorAll('.clue').length, locked: document.querySelectorAll('.clue.locked').length, q: /Next:/.test(t), btn: !![...document.querySelectorAll('button')].find(b => b.textContent === 'Ask for a story update'), contracts: !![...document.querySelectorAll('button')].find(b => b.textContent === 'Contracts'), leak: /kill_mfr|Relationship graph|Generation log|Recorded events|#\d+ /.test(t), dev: !!document.querySelector('.devd'), dash: /—/.test(document.querySelector('.fixcol').textContent), installed: /Installed /.test(t) }; });
ok(F.clues === 3 && F.locked === 2 && F.q && F.btn && F.contracts, 'fixer: current lead, 3 clue rows (2 locked with ?), story + contracts buttons'); ok(!F.leak && !F.dev && !F.dash && !F.installed, 'fixer: no debug leakage, no blank dashes, no stray install line when dev off');
await ev(() => { window.__game.save.settings.devFreeReset = true; window.__ui.render(); }); const D = await ev(() => { const d = document.querySelector('.devd'); return { has: !!d, open: d?.open, human: /Defeated 208/.test(d?.textContent || ''), raw: /kill_mfr|#\d+ /.test(d?.textContent || '') }; }); ok(D.has && !D.open && D.human && !D.raw, 'developer details: collapsed, humanized events');
await ev(() => { window.__ui.modal = 'contacts'; window.__ui.render(); }); ok(await ev(() => !/Portraits need art|never generated by the story system/.test(document.querySelector('#modal').textContent)), 'contacts: no debug-style text');
ok(errors.length === 0, 'no console errors ' + errors.join(';')); await browser.close(); if (fails) process.exit(1); console.log('panels ok');
