// CONTENT BATCH 1 (levels): 20 new dungeons as data. Layouts come from src/content/mapgen_batch1.ts (procedural, seeded, validated),
// bosses from batch1_bosses.ts. See docs/CONTENT_BATCH_1.md for the design table. Zone slots (yard/proc/junction/boss/salvage/passage) are reused by the run logic.
import { composeSquads, flatten } from './batch2_rosters';
import type { Squad } from './batch2_rosters';
export type Shape='open'|'pillars'|'rings'|'diag'|'cave'|'river'|'maze'|'islands'|'colonnade'|'pit'|'zigzag'|'cross';
export type HazMode='channels'|'scatter'|'ring'|'lanes'|'none';
export type Motif='stripes'|'grid'|'cracks'|'plates'|'hex'|'tiles'|'water'|'foam'|'crates';
export interface Pal { f:string; fm:string; w:string; wm:string; accent:string; light:'warm'|'cool'|'red'|'pale'; dust:string; motif:Motif; }
export interface LevelSpec {
  id:string; name:string; short:string; boss:string; mfr:'HI'|'PS'|'MM'; faction:string; district:string; tier:1|2|3|4; minLevel:number; maxLevel:number; est:[number,number];
  blurb:string; theme:string; pal:Pal;
  /** room shapes [yard, proc, junction, boss] + sizes [w,h] */ shapes:[Shape,Shape,Shape,Shape]; dims:[[number,number],[number,number],[number,number],[number,number]];
  haz:{ label:string; mode:HazMode; n:number; dps:number; heat:number; r:number };
  /** batch-2: mixed-role pack templates per zone (composed from batch2_rosters.ts); `roster` below is their flattened per-type totals */ squads?:Record<'yard'|'proc'|'junction'|'salvage',Squad[]>;
  roster:{ yard:[string,number][]; proc:[string,number][]; junction:[string,number][]; salvage:[string,number][] }; gateGuard:string; lockElite:string; alarmType:string;
  objective:{ label:string; relay:string; toast:string; bonus:string }; zoneLabels:Record<string,string>; props:{ crate:number; machine:number; rack:number; conveyor:number };
  unlock:{ after:string[] }; creditMul:number; xp:number; chips:[string,string]; loot:'HI'|'PS'|'MM'|'mix'; intro:string;
}
const T=(t:1|2|3|4)=>({1:{min:12,max:24},2:{min:20,max:32},3:{min:28,max:42},4:{min:38,max:50}}[t]);
export const LEVELS:LevelSpec[]=[
 { id:'coke_ovens', name:'Basin Coke Ovens', short:'Coke Ovens', boss:'voss', mfr:'HI', faction:'Harrow-Brandt', district:'Harrow Reach', tier:1, minLevel:T(1).min, maxLevel:T(1).max, est:[6,9], theme:'coke_ovens',
   blurb:'Condemned coke batteries that never stopped firing. Ember beds, charging rails and a battery floor for Marguerite Voss.',
   pal:{f:'rgba(110,70,40,.55)',fm:'rgb(150,126,110)',w:'rgba(96,58,34,.6)',wm:'rgb(150,128,112)',accent:'rgba(230,120,40,.7)',light:'red',dust:'220,140,80',motif:'cracks'},
   shapes:['open','colonnade','islands','pit'], dims:[[18,18],[28,22],[16,20],[22,24]], haz:{label:'Ember bed',mode:'channels',n:2,dps:8,heat:12,r:1.1},
   roster:{yard:[['slaghauler',7],['cinderhound',3]],proc:[['slaghauler',6],['ladlecrew',4],['cinderhound',4]],junction:[['ladlecrew',4],['slaghauler',3]],salvage:[['cinderhound',3]]}, gateGuard:'slagcannon', lockElite:'brakeman', alarmType:'slaghauler',
   objective:{label:'Battery charging controller',relay:'Charging-rail relay',toast:'Battery controller secured. The battery floor door opens.',bonus:'Quench-tower cache'}, zoneLabels:{yard:'Coke yard',proc:'Oven battery',junction:'Charging gantry',boss:'Battery floor',salvage:'Quench shed',passage:'Rail alcove'}, props:{crate:8,machine:3,rack:2,conveyor:2},
   unlock:{after:['annex']}, creditMul:1.5, xp:450, chips:['ablative','quench'], loot:'HI', intro:'Coke Ovens: shut the charging gate, take the controller, face Voss.' },
 { id:'substation_12', name:'Substation 12', short:'Substation', boss:'lineman', mfr:'HI', faction:'Harrow-Brandt', district:'Harrow Reach', tier:1, minLevel:T(1).min, maxLevel:T(1).max, est:[6,9], theme:'substation_12',
   blurb:'A live grid substation with breaker halls and transformer yards. Lineman Brandt keeps the lines hot.',
   pal:{f:'rgba(70,86,110,.6)',fm:'rgb(150,156,168)',w:'rgba(56,70,96,.65)',wm:'rgb(140,150,166)',accent:'rgba(240,210,70,.7)',light:'cool',dust:'160,190,230',motif:'stripes'},
   shapes:['pillars','rings','zigzag','colonnade'], dims:[[20,16],[26,22],[16,18],[24,22]], haz:{label:'Live bus bar',mode:'lanes',n:3,dps:9,heat:8,r:1.0},
   roster:{yard:[['worker',6],['shooter',4]],proc:[['shooter',5],['turret',0],['sawhand',0],['worker',5]],junction:[['shooter',4],['worker',4]],salvage:[['worker',4]]}, gateGuard:'turret', lockElite:'sawhand', alarmType:'shooter',
   objective:{label:'Grid interlock',relay:'Breaker relay',toast:'Grid interlock thrown. The control hall opens.',bonus:'Spares locker'}, zoneLabels:{yard:'Transformer yard',proc:'Breaker hall',junction:'Switch gallery',boss:'Control hall',salvage:'Spares room',passage:'Cable run'}, props:{crate:5,machine:6,rack:3,conveyor:0},
   unlock:{after:['warehouse']}, creditMul:1.5, xp:460, chips:['power','coolant'], loot:'HI', intro:'Substation 12: kill the yard guns, throw the interlock, take the hall from Lineman Brandt.' },
 { id:'scrap_gantry', name:'Rustline Scrap Gantry', short:'Scrap Gantry', boss:'gantrymother', mfr:'MM', faction:'Rustline Compact', district:'Rustline Market', tier:1, minLevel:T(1).min, maxLevel:T(1).max, est:[5,8], theme:'scrap_gantry',
   blurb:'A cluttered scrap yard under travelling cranes. Mounds of salvage make maze-like lanes for the Gantry-Mother.',
   pal:{f:'rgba(110,100,60,.55)',fm:'rgb(160,150,120)',w:'rgba(100,84,50,.6)',wm:'rgb(150,140,116)',accent:'rgba(210,170,60,.7)',light:'warm',dust:'200,180,120',motif:'crates'},
   shapes:['islands','maze','islands','open'], dims:[[22,18],[30,22],[16,18],[20,22]], haz:{label:'Crane drop zone',mode:'scatter',n:6,dps:9,heat:6,r:1.5},
   roster:{yard:[['picker',8],['loader',2]],proc:[['picker',6],['loader',3],['forkbot',3]],junction:[['scanner',4],['picker',4]],salvage:[['forkbot',3]]}, gateGuard:'camgun', lockElite:'hobbs', alarmType:'picker',
   objective:{label:'Crane master console',relay:'Magnet relay',toast:'Crane console seized. The big gantry door opens.',bonus:'Salvage bin'}, zoneLabels:{yard:'Scrap yard',proc:'Salvage mounds',junction:'Crane cab row',boss:'Gantry floor',salvage:'Spare-parts shed',passage:'Rail spur'}, props:{crate:14,machine:2,rack:2,conveyor:3},
   unlock:{after:['warehouse']}, creditMul:1.4, xp:430, chips:['magnet','speed'], loot:'MM', intro:'Scrap Gantry: work the scrap lanes, seize the crane console, and face the Gantry-Mother.' },
 { id:'tailings_pit', name:'Tailings Pit 3', short:'Tailings Pit', boss:'pitboss', mfr:'HI', faction:'Harrow-Brandt', district:'Harrow Reach', tier:1, minLevel:T(1).min, maxLevel:T(1).max, est:[6,9], theme:'tailings_pit',
   blurb:'An open pit with switchback ramps and sludge pools. Karl Ossendrecht still runs the shift.',
   pal:{f:'rgba(120,100,60,.5)',fm:'rgb(160,146,120)',w:'rgba(110,90,54,.6)',wm:'rgb(150,140,120)',accent:'rgba(170,150,80,.6)',light:'warm',dust:'190,170,120',motif:'plates'},
   shapes:['diag','cave','diag','pit'], dims:[[22,20],[28,24],[16,20],[24,26]], haz:{label:'Sludge pool',mode:'scatter',n:7,dps:8,heat:8,r:1.6},
   roster:{yard:[['slaghauler',6],['loader',3]],proc:[['slaghauler',6],['cinderhound',4],['loader',3]],junction:[['ladlecrew',4]],salvage:[['slaghauler',3]]}, gateGuard:'slagcannon', lockElite:'sawhand', alarmType:'slaghauler',
   objective:{label:'Haul-road relay',relay:'Ramp relay',toast:'Haul-road relay online. The pit floor opens.',bonus:'Assay cache'}, zoneLabels:{yard:'Pit rim',proc:'Switchback ramps',junction:'Haul-road post',boss:'Pit floor',salvage:'Assay hut',passage:'Cut-through'}, props:{crate:6,machine:4,rack:1,conveyor:1},
   unlock:{after:['annex']}, creditMul:1.5, xp:450, chips:['plating','ablative'], loot:'HI', intro:'Tailings Pit 3: climb down the ramps, restart the haul road, take on Ossendrecht.' },
 { id:'bell_foundry', name:'Calloway Bell Foundry', short:'Bell Foundry', boss:'bellfounder', mfr:'HI', faction:'Harrow-Brandt', district:'Harrow Reach', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[7,10], theme:'bell_foundry',
   blurb:'A cathedral-height foundry of cast bells and hanging moulds. Vesper Calloway rings them all.',
   pal:{f:'rgba(110,84,50,.55)',fm:'rgb(160,140,110)',w:'rgba(120,88,44,.6)',wm:'rgb(160,140,112)',accent:'rgba(210,170,70,.7)',light:'warm',dust:'210,170,100',motif:'plates'},
   shapes:['colonnade','rings','pillars','rings'], dims:[[20,20],[28,26],[18,22],[26,26]], haz:{label:'Bronze melt',mode:'ring',n:8,dps:10,heat:14,r:1.3},
   roster:{yard:[['slaghauler',6],['ladlecrew',3]],proc:[['ladlecrew',5],['quenchpriest',0],['slaghauler',5],['cinderhound',3]],junction:[['ladlecrew',4],['slaghauler',4]],salvage:[['cinderhound',3]]}, gateGuard:'slagcannon', lockElite:'quenchpriest', alarmType:'slaghauler',
   objective:{label:'Great bell mechanism',relay:'Chime relay',toast:'Great bell mechanism locked. The founding hall opens.',bonus:'Mould-loft cache'}, zoneLabels:{yard:'Mould yard',proc:'Bell casting hall',junction:'Chime gallery',boss:'Founding hall',salvage:'Mould loft',passage:'Bell stair'}, props:{crate:5,machine:5,rack:3,conveyor:1},
   unlock:{after:['foundry']}, creditMul:2.4, xp:700, chips:['quench','overdrive'], loot:'HI', intro:'Bell Foundry: silence the yard guns, lock the great bell, and endure the toll.' },
 { id:'cold_archive', name:'Aldane Cold Archive', short:'Cold Archive', boss:'cryo', mfr:'PS', faction:'Aldane Surgical', district:'Aldane Terrace', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'cold_archive',
   blurb:'Frozen records vaults, rime-covered stacks and cold lanes. Frost keeps the files.',
   pal:{f:'rgba(150,180,200,.6)',fm:'rgb(210,222,230)',w:'rgba(120,150,176,.65)',wm:'rgb(200,214,224)',accent:'rgba(160,220,240,.7)',light:'pale',dust:'210,230,245',motif:'tiles'},
   shapes:['maze','zigzag','maze','open'], dims:[[18,20],[30,24],[16,20],[22,24]], haz:{label:'Frost vent',mode:'scatter',n:6,dps:8,heat:6,r:1.5},
   roster:{yard:[['orderly',6],['nursebot',3]],proc:[['orderly',5],['nursebot',4],['gurneyrunner',3]],junction:[['nursebot',4],['orderly',4]],salvage:[['gurneyrunner',3]]}, gateGuard:'sentry', lockElite:'matron', alarmType:'orderly',
   objective:{label:'Stack index terminal',relay:'Cryo relay',toast:'Stack index unlocked. The deep vault door opens.',bonus:'Sealed case file'}, zoneLabels:{yard:'Intake bay',proc:'Frozen stacks',junction:'Index room',boss:'Deep vault',salvage:'Thaw room',passage:'Pipe chase'}, props:{crate:4,machine:3,rack:8,conveyor:0},
   unlock:{after:['clinic']}, creditMul:2.3, xp:690, chips:['cloakdur','gridlink'], loot:'PS', intro:'Cold Archive: thaw the stacks, unlock the index, and face Frost.' },
 { id:'audit_tower', name:'Aldane Audit Tower', short:'Audit Tower', boss:'auditor', mfr:'PS', faction:'Aldane Surgical', district:'Aldane Terrace', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'audit_tower',
   blurb:'A glass-and-ceramic compliance tower of open-plan floors. Thornquist audits everything.',
   pal:{f:'rgba(160,170,176,.6)',fm:'rgb(200,206,208)',w:'rgba(110,130,140,.6)',wm:'rgb(190,198,202)',accent:'rgba(80,170,170,.7)',light:'pale',dust:'200,215,220',motif:'grid'},
   shapes:['pillars','cross','colonnade','cross'], dims:[[20,20],[28,22],[18,20],[24,24]], haz:{label:'Audit laser',mode:'lanes',n:3,dps:9,heat:6,r:1.0},
   roster:{yard:[['orderly',6],['nursebot',4]],proc:[['nursebot',6],['orderly',4]],junction:[['nursebot',4],['gurneyrunner',3]],salvage:[['orderly',3]]}, gateGuard:'sentry', lockElite:'anesthetist', alarmType:'nursebot',
   objective:{label:'Findings ledger',relay:'Compliance relay',toast:'Ledger signed. The audit chamber opens.',bonus:'Exemption slip cache'}, zoneLabels:{yard:'Reception atrium',proc:'Open-plan floor',junction:'Review gallery',boss:'Audit chamber',salvage:'Records closet',passage:'Fire stair'}, props:{crate:3,machine:5,rack:4,conveyor:0},
   unlock:{after:['cold_archive']}, creditMul:2.3, xp:690, chips:['gridlink','fineedge'], loot:'PS', intro:'Audit Tower: pass reception, sign the ledger, survive the audit.' },
 { id:'aesthetic_ward', name:'Ward 3 Aesthetics', short:'Aesthetic Ward', boss:'mirrorpt', mfr:'PS', faction:'Aldane Surgical', district:'Aldane Terrace', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'aesthetic_ward',
   blurb:'Elective-revision suites lined with mirrors. Every room has the same woman in it.',
   pal:{f:'rgba(190,170,170,.6)',fm:'rgb(220,208,206)',w:'rgba(150,130,136,.6)',wm:'rgb(206,196,198)',accent:'rgba(210,130,150,.7)',light:'pale',dust:'230,210,214',motif:'tiles'},
   shapes:['rings','maze','islands','zigzag'], dims:[[18,18],[26,24],[18,18],[24,24]], haz:{label:'Spilled sedative',mode:'scatter',n:6,dps:7,heat:5,r:1.5},
   roster:{yard:[['nursebot',5],['orderly',4]],proc:[['orderly',5],['gurneyrunner',3],['nursebot',4]],junction:[['nursebot',5]],salvage:[['orderly',3]]}, gateGuard:'sentry', lockElite:'matron', alarmType:'orderly',
   objective:{label:'Revision schedule board',relay:'Suite relay',toast:'Schedule rewritten. The mirror hall opens.',bonus:'Consent-form safe'}, zoneLabels:{yard:'Consultation hall',proc:'Revision suites',junction:'Recovery lounge',boss:'Mirror hall',salvage:'Supply closet',passage:'Service hall'}, props:{crate:3,machine:3,rack:5,conveyor:0},
   unlock:{after:['clinic']}, creditMul:2.3, xp:680, chips:['cloakdur','sustain'], loot:'PS', intro:'Ward 3: wander the suites, rewrite the schedule, break the mirror.' },
 { id:'pharmacy_vault', name:'Quill Pharmacy Vault', short:'Pharmacy Vault', boss:'apothecary', mfr:'PS', faction:'Aldane Surgical', district:'Aldane Terrace', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'pharmacy_vault',
   blurb:'A sealed dispensary vault of cabinets and gas lines. Dessa Quill still fills prescriptions.',
   pal:{f:'rgba(110,150,130,.6)',fm:'rgb(184,206,196)',w:'rgba(80,120,104,.6)',wm:'rgb(176,198,188)',accent:'rgba(120,210,150,.7)',light:'pale',dust:'190,225,205',motif:'hex'},
   shapes:['maze','islands','cross','pillars'], dims:[[18,20],[28,22],[16,20],[22,24]], haz:{label:'Gas leak',mode:'scatter',n:8,dps:7,heat:4,r:1.7},
   roster:{yard:[['orderly',5],['nursebot',4]],proc:[['nursebot',6],['orderly',4],['gurneyrunner',2]],junction:[['nursebot',4],['orderly',3]],salvage:[['orderly',3]]}, gateGuard:'sentry', lockElite:'anesthetist', alarmType:'orderly',
   objective:{label:'Dispensary controller',relay:'Cabinet relay',toast:'Dispensary locked down. The vault door opens.',bonus:'Controlled-stock cabinet'}, zoneLabels:{yard:'Counter hall',proc:'Cabinet aisles',junction:'Compounding bay',boss:'Vault floor',salvage:'Returns bin',passage:'Pneumatic tube'}, props:{crate:4,machine:3,rack:7,conveyor:0},
   unlock:{after:['aesthetic_ward']}, creditMul:2.4, xp:700, chips:['sustain','quench'], loot:'PS', intro:'Pharmacy Vault: hold your breath, lock the dispensary, close Quill\'s prescription.' },
 { id:'anechoic_lab', name:'Lindqvist Anechoic Lab', short:'Anechoic Lab', boss:'resonance', mfr:'PS', faction:'Aldane Surgical', district:'Aldane Terrace', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'anechoic_lab',
   blurb:'Foam-wedge chambers built to swallow sound. The corridors hum. Obi Lindqvist hears everything.',
   pal:{f:'rgba(70,74,80,.65)',fm:'rgb(130,136,142)',w:'rgba(54,58,64,.7)',wm:'rgb(116,122,128)',accent:'rgba(120,170,200,.6)',light:'cool',dust:'150,160,172',motif:'foam'},
   shapes:['pillars','diag','colonnade','rings'], dims:[[20,18],[28,24],[18,22],[26,26]], haz:{label:'Resonance field',mode:'ring',n:7,dps:11,heat:6,r:1.3},
   roster:{yard:[['nursebot',5],['orderly',4]],proc:[['nursebot',6],['gurneyrunner',4],['orderly',4]],junction:[['anesthetist',0],['nursebot',5]],salvage:[['gurneyrunner',3]]}, gateGuard:'sentry', lockElite:'anesthetist', alarmType:'nursebot',
   objective:{label:'Calibration rig',relay:'Isolation relay',toast:'Calibration rig seized. The anechoic cell opens.',bonus:'Instrument case'}, zoneLabels:{yard:'Vestibule',proc:'Foam corridors',junction:'Calibration bay',boss:'Anechoic cell',salvage:'Instrument store',passage:'Baffle duct'}, props:{crate:3,machine:5,rack:3,conveyor:0},
   unlock:{after:['audit_tower']}, creditMul:3.3, xp:1000, chips:['gridlink','overdrive'], loot:'PS', intro:'Anechoic Lab: listen for the hum, take the rig, and survive the silence.' },
 { id:'outlet_mall', name:'Kestrel Outlet Mall', short:'Outlet Mall', boss:'clearance', mfr:'MM', faction:'Kestrel Value', district:'Kestrel Row', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'outlet_mall',
   blurb:'A dead mall with the lights still on. Faded markdown banners, shuttered storefronts, a central atrium sale.',
   pal:{f:'rgba(130,110,130,.55)',fm:'rgb(180,170,176)',w:'rgba(120,96,120,.6)',wm:'rgb(176,166,174)',accent:'rgba(190,100,140,.65)',light:'warm',dust:'210,190,200',motif:'tiles'},
   shapes:['islands','colonnade','islands','rings'], dims:[[22,18],[30,20],[18,20],[26,24]], haz:{label:'Sale spill',mode:'scatter',n:6,dps:7,heat:4,r:1.6},
   roster:{yard:[['picker',7],['scanner',3]],proc:[['picker',6],['scanner',4],['loader',3],['forkbot',3]],junction:[['scanner',5],['picker',4]],salvage:[['picker',4]]}, gateGuard:'camgun', lockElite:'shiftlead', alarmType:'picker',
   objective:{label:'Doorbuster register',relay:'Shutter relay',toast:'Register cleared. The atrium doors open.',bonus:'Lost-and-found'}, zoneLabels:{yard:'Entrance court',proc:'Storefront row',junction:'Food court',boss:'Atrium',salvage:'Stockroom',passage:'Service corridor'}, props:{crate:8,machine:2,rack:5,conveyor:1},
   unlock:{after:['scrap_gantry']}, creditMul:2.0, xp:640, chips:['ablative','speed'], loot:'MM', intro:'Outlet Mall: clear the court, empty the register, shut down the sale.' },
 { id:'liquidation_floor', name:'Kestrel Liquidation Floor', short:'Liquidation', boss:'liquidator', mfr:'MM', faction:'Kestrel Value', district:'Kestrel Row', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'liquidation_floor',
   blurb:'A receivership floor of tagged pallets and red-ticket stacks. Everything is priced to move; so are you.',
   pal:{f:'rgba(140,90,80,.55)',fm:'rgb(176,150,142)',w:'rgba(124,70,64,.6)',wm:'rgb(170,146,140)',accent:'rgba(210,80,70,.7)',light:'red',dust:'210,170,160',motif:'stripes'},
   shapes:['zigzag','islands','zigzag','pit'], dims:[[22,20],[30,24],[18,22],[26,26]], haz:{label:'Tagged pallet fire',mode:'scatter',n:7,dps:10,heat:10,r:1.4},
   roster:{yard:[['loader',5],['picker',5]],proc:[['loader',5],['forkbot',4],['scanner',4]],junction:[['scanner',5],['picker',4]],salvage:[['forkbot',3]]}, gateGuard:'camgun', lockElite:'hobbs', alarmType:'loader',
   objective:{label:'Receivership ledger',relay:'Auction relay',toast:'Ledger frozen. The auction floor opens.',bonus:'Seized-goods cage'}, zoneLabels:{yard:'Receiving dock',proc:'Tagged stacks',junction:'Appraisal office',boss:'Auction floor',salvage:'Seized-goods cage',passage:'Pallet lane'}, props:{crate:12,machine:3,rack:5,conveyor:2},
   unlock:{after:['outlet_mall']}, creditMul:3.2, xp:980, chips:['fineedge','quench'], loot:'MM', intro:'Liquidation Floor: freeze the ledger and survive the auction.' },
 { id:'parcel_tower', name:'Kestrel Parcel Tower', short:'Parcel Tower', boss:'courier', mfr:'MM', faction:'Kestrel Value', district:'Kestrel Row', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'parcel_tower',
   blurb:'Sorting floors stacked in a tower, chutes and belts everywhere. Marisol Pike keeps the line moving.',
   pal:{f:'rgba(150,120,80,.55)',fm:'rgb(180,160,130)',w:'rgba(130,100,64,.6)',wm:'rgb(172,152,124)',accent:'rgba(210,150,60,.7)',light:'warm',dust:'210,180,130',motif:'crates'},
   shapes:['colonnade','diag','river','open'], dims:[[22,18],[30,22],[18,20],[26,22]], haz:{label:'Chute drop',mode:'lanes',n:4,dps:10,heat:5,r:1.2},
   roster:{yard:[['picker',6],['forkbot',3]],proc:[['forkbot',5],['picker',5],['scanner',4]],junction:[['scanner',5],['loader',3]],salvage:[['forkbot',3]]}, gateGuard:'camgun', lockElite:'shiftlead', alarmType:'forkbot',
   objective:{label:'Master dispatch belt',relay:'Belt relay',toast:'Dispatch belt stopped. The express floor opens.',bonus:'Misrouted crate'}, zoneLabels:{yard:'Receiving floor',proc:'Sorting belts',junction:'Dispatch deck',boss:'Express floor',salvage:'Dead-letter room',passage:'Chute'}, props:{crate:10,machine:2,rack:3,conveyor:6},
   unlock:{after:['liquidation_floor']}, creditMul:3.3, xp:990, chips:['speed','magnet'], loot:'MM', intro:'Parcel Tower: stop the belt and beat the Courier-Queen to the punch.' },
 { id:'freight_depot', name:'Basin Freight Depot', short:'Freight Depot', boss:'dispatcher', mfr:'MM', faction:'Kestrel Value', district:'Kestrel Row', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'freight_depot',
   blurb:'Rail sidings, container stacks and a dead dispatch tower. AUTO-7 still routes the trains.',
   pal:{f:'rgba(70,96,84,.6)',fm:'rgb(140,160,150)',w:'rgba(56,80,70,.65)',wm:'rgb(132,152,142)',accent:'rgba(220,190,60,.65)',light:'cool',dust:'160,190,175',motif:'stripes'},
   shapes:['river','islands','maze','colonnade'], dims:[[24,18],[32,22],[18,20],[26,24]], haz:{label:'Live rail',mode:'channels',n:2,dps:10,heat:6,r:1.0},
   roster:{yard:[['forkbot',4],['picker',5],['scanner',3]],proc:[['forkbot',5],['loader',4],['scanner',4]],junction:[['scanner',5],['picker',3]],salvage:[['loader',3]]}, gateGuard:'camgun', lockElite:'hobbs', alarmType:'forkbot',
   objective:{label:'Signal tower relay',relay:'Points relay',toast:'Signal tower seized. The marshalling yard opens.',bonus:'Reefer container'}, zoneLabels:{yard:'Siding yard',proc:'Container stacks',junction:'Signal gantry',boss:'Marshalling yard',salvage:'Reefer cage',passage:'Under-track culvert'}, props:{crate:12,machine:3,rack:2,conveyor:3},
   unlock:{after:['substation_12','scrap_gantry']}, creditMul:3.3, xp:1000, chips:['gridlink','magnet'], loot:'MM', intro:'Freight Depot: cross the live rail, seize the tower, stop AUTO-7.' },
 { id:'warranty_vault', name:'Kestrel Warranty Vault', short:'Warranty Vault', boss:'warrantor', mfr:'MM', faction:'Kestrel Value', district:'Kestrel Row', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'warranty_vault',
   blurb:'A bonded vault of void-warranty files and returned units. Edda Marsh denies by default.',
   pal:{f:'rgba(130,120,80,.55)',fm:'rgb(172,164,138)',w:'rgba(110,96,60,.65)',wm:'rgb(164,156,132)',accent:'rgba(220,180,70,.75)',light:'warm',dust:'210,196,150',motif:'plates'},
   shapes:['pillars','cross','rings','cross'], dims:[[20,18],[26,24],[18,22],[26,26]], haz:{label:'Seal field',mode:'ring',n:8,dps:10,heat:8,r:1.3},
   roster:{yard:[['loader',5],['scanner',4]],proc:[['scanner',5],['picker',5],['forkbot',3]],junction:[['shiftlead',0],['scanner',5],['loader',3]],salvage:[['picker',3]]}, gateGuard:'camgun', lockElite:'shiftlead', alarmType:'scanner',
   objective:{label:'Claims terminal',relay:'Vault relay',toast:'Claims terminal overridden. The vault door opens.',bonus:'Void-warranty box'}, zoneLabels:{yard:'Claims lobby',proc:'File aisles',junction:'Adjuster desks',boss:'Vault floor',salvage:'Returned units',passage:'Bonded passage'}, props:{crate:6,machine:3,rack:6,conveyor:1},
   unlock:{after:['liquidation_floor']}, creditMul:3.4, xp:1020, chips:['ablative','fineedge'], loot:'MM', intro:'Warranty Vault: override the claims terminal; your warranty is void.' },
 { id:'drained_reservoir', name:'Drained Reservoir', short:'Reservoir', boss:'tidewarden', mfr:'MM', faction:'Rustline Compact', district:'Rustline Market', tier:2, minLevel:T(2).min, maxLevel:T(2).max, est:[6,9], theme:'drained_reservoir',
   blurb:'The Basin reservoir, empty and tide-stained. Pump halls and spillways, with Alva Strand still on watch.',
   pal:{f:'rgba(70,110,110,.55)',fm:'rgb(150,172,170)',w:'rgba(56,92,92,.6)',wm:'rgb(144,166,164)',accent:'rgba(80,170,170,.65)',light:'cool',dust:'150,190,190',motif:'water'},
   shapes:['river','cave','river','pit'], dims:[[22,20],[30,24],[18,22],[26,26]], haz:{label:'Standing water',mode:'channels',n:2,dps:6,heat:3,r:1.2},
   roster:{yard:[['slaghauler',4],['picker',4],['cinderhound',2]],proc:[['picker',5],['loader',3],['slaghauler',4]],junction:[['ladlecrew',3],['scanner',3]],salvage:[['picker',3]]}, gateGuard:'camgun', lockElite:'hobbs', alarmType:'picker',
   objective:{label:'Sluice controller',relay:'Pump relay',toast:'Sluice controller secured. The spillway opens.',bonus:'Pump-house locker'}, zoneLabels:{yard:'Intake channel',proc:'Pump halls',junction:'Sluice gallery',boss:'Spillway floor',salvage:'Pump house',passage:'Drain culvert'}, props:{crate:4,machine:5,rack:1,conveyor:1},
   unlock:{after:['tailings_pit']}, creditMul:2.2, xp:660, chips:['coolant','sustain'], loot:'mix', intro:'Drained Reservoir: cross the channels, throw the sluice, and face the Pump-Warden.' },
 { id:'night_tunnels', name:'Quiet Shift Tunnels', short:'Night Tunnels', boss:'rattle', mfr:'MM', faction:'Quiet Shift', district:'Rustline Market', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'night_tunnels',
   blurb:'Service tunnels where the Quiet Shift still clock in. Low light, tight bends and a foreman who counts heads.',
   pal:{f:'rgba(44,52,76,.7)',fm:'rgb(110,118,140)',w:'rgba(34,40,62,.75)',wm:'rgb(96,104,128)',accent:'rgba(110,130,190,.6)',light:'cool',dust:'120,130,170',motif:'grid'},
   shapes:['cave','maze','cave','zigzag'], dims:[[20,20],[30,24],[16,22],[24,24]], haz:{label:'Sump water',mode:'scatter',n:6,dps:7,heat:3,r:1.5},
   roster:{yard:[['worker',7],['shooter',4]],proc:[['worker',7],['shooter',5],['foreman',0],['picker',3]],junction:[['shooter',5],['worker',4]],salvage:[['worker',4]]}, gateGuard:'turret', lockElite:'foreman', alarmType:'worker',
   objective:{label:'Shift-bell box',relay:'Tunnel relay',toast:'Shift bell silenced. The mess hall opens.',bonus:'Lunch-pail stash'}, zoneLabels:{yard:'Clock-in hall',proc:'Service tunnels',junction:'Crew junction',boss:'Mess hall',salvage:'Locker room',passage:'Crawlway'}, props:{crate:6,machine:2,rack:3,conveyor:1},
   unlock:{after:['drained_reservoir']}, creditMul:3.0, xp:960, chips:['cloakdur','speed'], loot:'mix', intro:'Night Tunnels: keep to the bends, silence the bell, face Rattle.' },
 { id:'breaker_yard', name:'Kellan Breaker Yard', short:'Breaker Yard', boss:'breaker', mfr:'HI', faction:'Rustline Compact', district:'Rustline Market', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'breaker_yard',
   blurb:'Where decommissioned hardware is stripped for parts. Gutted frames, hanging chains and a rubble pit.',
   pal:{f:'rgba(120,70,50,.6)',fm:'rgb(160,128,112)',w:'rgba(110,54,36,.65)',wm:'rgb(156,124,108)',accent:'rgba(220,100,50,.7)',light:'red',dust:'200,140,110',motif:'cracks'},
   shapes:['islands','diag','zigzag','pit'], dims:[[22,20],[30,24],[18,22],[26,26]], haz:{label:'Scrap fire',mode:'scatter',n:8,dps:10,heat:12,r:1.4},
   roster:{yard:[['slaghauler',6],['worker',4],['sawhand',0]],proc:[['slaghauler',6],['ladlecrew',4],['cinderhound',4]],junction:[['ladlecrew',4],['worker',4]],salvage:[['cinderhound',3]]}, gateGuard:'slagcannon', lockElite:'sawhand', alarmType:'slaghauler',
   objective:{label:'Crusher controller',relay:'Chain relay',toast:'Crusher controller seized. The stripping pit opens.',bonus:'Parts bin'}, zoneLabels:{yard:'Chain yard',proc:'Stripping lanes',junction:'Crusher gantry',boss:'Stripping pit',salvage:'Parts bin',passage:'Chute'}, props:{crate:10,machine:4,rack:2,conveyor:2},
   unlock:{after:['bell_foundry']}, creditMul:3.2, xp:980, chips:['plating','overdrive'], loot:'HI', intro:'Breaker Yard: strip it down before the Breaker-King strips you.' },
 { id:'radio_mast', name:'Basin Radio Mast', short:'Radio Mast', boss:'widow', mfr:'PS', faction:'Rustline Compact', district:'Aldane Terrace', tier:3, minLevel:T(3).min, maxLevel:T(3).max, est:[7,10], theme:'radio_mast',
   blurb:'A broadcast mast on a gantry platform, antenna arrays and cable trays. Perpetua relays what she chooses.',
   pal:{f:'rgba(100,110,130,.55)',fm:'rgb(160,168,180)',w:'rgba(84,92,112,.6)',wm:'rgb(150,158,172)',accent:'rgba(220,170,90,.65)',light:'cool',dust:'170,180,200',motif:'hex'},
   shapes:['diag','pillars','river','colonnade'], dims:[[22,18],[28,22],[18,20],[26,24]], haz:{label:'RF burn',mode:'lanes',n:3,dps:10,heat:8,r:1.1},
   roster:{yard:[['nursebot',4],['shooter',4],['orderly',3]],proc:[['nursebot',5],['shooter',5],['gurneyrunner',3]],junction:[['nursebot',4],['shooter',4]],salvage:[['shooter',3]]}, gateGuard:'sentry', lockElite:'matron', alarmType:'shooter',
   objective:{label:'Transmitter core',relay:'Feeder relay',toast:'Transmitter core cut. The antenna deck opens.',bonus:'Spare feedline'}, zoneLabels:{yard:'Base compound',proc:'Cable galleries',junction:'Transmitter room',boss:'Antenna deck',salvage:'Battery room',passage:'Cable tray'}, props:{crate:4,machine:5,rack:4,conveyor:0},
   unlock:{after:['pharmacy_vault']}, creditMul:3.2, xp:980, chips:['gridlink','cloakdur'], loot:'PS', intro:'Radio Mast: climb the compound, cut the transmitter, face Perpetua.' },
 { id:'recall_yard', name:'Recall Authority Yard', short:'Recall Yard', boss:'recall', mfr:'HI', faction:'Recall Authority', district:'Verge Basin', tier:4, minLevel:T(4).min, maxLevel:T(4).max, est:[9,13], theme:'recall_yard',
   blurb:'The Basin graveyard of recalled hardware from all three manufacturers. R-ALL is still issuing recalls.',
   pal:{f:'rgba(90,86,96,.6)',fm:'rgb(150,148,156)',w:'rgba(70,66,80,.65)',wm:'rgb(140,138,148)',accent:'rgba(200,70,70,.7)',light:'red',dust:'170,160,170',motif:'hex'},
   shapes:['maze','rings','pillars','rings'], dims:[[22,20],[32,26],[20,24],[28,28]], haz:{label:'Recall beacon',mode:'ring',n:9,dps:12,heat:10,r:1.3},
   roster:{yard:[['worker',4],['picker',4],['orderly',4]],proc:[['shooter',4],['nursebot',4],['ladlecrew',4],['forkbot',3]],junction:[['slaghauler',4],['scanner',4],['nursebot',3]],salvage:[['cinderhound',3],['gurneyrunner',2]]}, gateGuard:'turret', lockElite:'brakeman', alarmType:'shooter',
   objective:{label:'Recall registry',relay:'Registry relay',toast:'Recall registry corrupted. The recall chamber opens.',bonus:'Impounded hardware'}, zoneLabels:{yard:'Impound lot',proc:'Recall rows',junction:'Registry hall',boss:'Recall chamber',salvage:'Impound cage',passage:'Conveyor tunnel'}, props:{crate:8,machine:4,rack:4,conveyor:2},
   unlock:{after:['breaker_yard','radio_mast','warranty_vault']}, creditMul:5.0, xp:1800, chips:['overdrive','quench'], loot:'mix', intro:'Recall Yard: every manufacturer\'s mistakes are here. Corrupt the registry and end the recall.' },
];
// batch 2: tier-progressive mob rosters (docs/MOBS_BATCH_2.md). Overrides the batch-1 placeholder rosters above.
for(const L of LEVELS){ const zs=['yard','proc','junction','salvage'] as const; const sq:any={}, ro:any={}; for(const z of zs){ sq[z]=composeSquads(L.id,L.tier,z); ro[z]=flatten(sq[z]); } L.squads=sq; L.roster=ro; }
export const LEVEL_BY_ID:Record<string,LevelSpec>=Object.fromEntries(LEVELS.map(l=>[l.id,l]));
