// CONTENT BATCH 2 (mobs): 28 tier-progressive mobs as DATA (docs/MOBS_BATCH_2.md). Built on the batch-1 mechanics toolkit: every mob's special attacks
// are MoveSpecs (fan / nova / marks / rain / ring / cross ...) compiled into attack ids "<mob>.<n>" by boss_moves.ts, plus a handful of mob-only attacks
// (snipe, mend, ward, hex, detonate, summonlite) whose runtime lives in src/content/mobs.ts. Elite AFFIXES (hasted, volatile, shielded, ...) also live there.
// PLACEHOLDER balance, like the rest of the prototype. This file is data only (no sim/config imports) so config.ts, boss_moves.ts and the level generator can all read it.
import type { MoveSpec } from './batch1_bosses';
import { BAL } from './balance';
export type Role='swarmer'|'bruiser'|'ranged'|'caster'|'shielded'|'exploder'|'summoner'|'sniper'|'charger'|'healer'|'debuffer'|'support';
export type FacTag='HB'|'AS'|'KV'|'RC'|'QS'|'RA';
export interface MobMeta { tier:1|2|3|4; role:Role; fac:FacTag[]; lifesteal?:number; shield?:number; keep?:number; hasted?:boolean; }
export interface MobSpec {
  id:string; name:string; tier:1|2|3|4; role:Role; fac:FacTag[]; mfr:'HI'|'PS'|'MM'; blurb:string;
  hp:number; speed:number; radius:number; aggro:number; xp:number; dmg:number;
  /** existing melee/ranged attack ids */ melee:string[]; /** toolkit moves -> "<id>.<n>" */ moves:MoveSpec[]; /** mob-only attack ids (see MOB_ATK) */ custom?:string[];
  summon?:string; ranged?:boolean; shield?:number; keep?:number; lifesteal?:number; hasted?:boolean;
  /** world height (tiles), hover height */ h:number; hover?:number; /** flat sprite used only while the atlas loads */ spr:string; /** [min,max] pack size hint */ pack:[number,number];
}
/** per-tier multipliers applied to the raw numbers in MOBS (hp/dmg are already authored per tier; this documents the intended curve) */
export const TIER_CURVE:Record<number,{hp:number;dmg:number;elite:number;affixes:number}>={ 1:{hp:1,dmg:1.25,elite:BAL.elite[1]??.10,affixes:1}, 2:{hp:1.7,dmg:1.45,elite:BAL.elite[2]??.18,affixes:1}, 3:{hp:2.7,dmg:1.65,elite:BAL.elite[3]??.28,affixes:2}, 4:{hp:4,dmg:1.9,elite:BAL.elite[4]??.40,affixes:3} };
const M=(m:MobSpec)=>m;
export const MOBS:MobSpec[]=[
 // ------------------------------------------------ TIER I
 M({ id:'cindermite', name:'Cinder Mite', tier:1, role:'swarmer', fac:['HB','RC'], mfr:'HI', blurb:'Palm-sized coke-oven vermin that hatch in the ember beds and swarm anything warm.', hp:9, speed:4.7, radius:.3, aggro:8, xp:4, dmg:1.25, melee:['bite'], moves:[], h:.62, spr:'cinderhound', pack:[7,10] }),
 M({ id:'coalheaver', name:'Coal Heaver', tier:1, role:'bruiser', fac:['HB'], mfr:'HI', blurb:'Oven-door labourer in a soot-black rig. Slow, strong, hits like a charging-rail.', hp:64, speed:2.5, radius:.55, aggro:8, xp:20, dmg:1.3, melee:['cleave','slam'], moves:[], h:1.5, spr:'sawhand', pack:[2,3] }),
 M({ id:'arcflinger', name:'Arc Flinger', tier:1, role:'ranged', fac:['HB','RC'], mfr:'HI', blurb:'Lineman cast-off with a coil lance. Throws a three-bolt arc fan.', hp:28, speed:2.4, radius:.38, aggro:10, xp:14, dmg:1.25, melee:['shot'], ranged:true, moves:[{k:'fan',p:{n:3,spread:26,speed:12},w:.8,cd:3.4,min:2,max:12,dmg:9}], h:1.15, spr:'shooter', pack:[2,4] }),
 M({ id:'scrapram', name:'Scrap Ram', tier:1, role:'charger', fac:['RC','KV'], mfr:'MM', blurb:'A welded-together ram beast. Lowers its plate and charges in a straight line.', hp:50, speed:3.4, radius:.52, aggro:9, xp:17, dmg:1.1, melee:['charge','bite'], moves:[], h:.88, spr:'cinderhound', pack:[1,3] }),
 M({ id:'fusecrawler', name:'Fuse Crawler', tier:1, role:'exploder', fac:['HB','RC','KV'], mfr:'HI', blurb:'A crawler with a swollen glowing sac. Rushes you and detonates after a short fuse.', hp:16, speed:4.2, radius:.34, aggro:9, xp:10, dmg:1.25, melee:[], moves:[], custom:['detonate'], h:.78, spr:'cinderhound', pack:[3,5] }),
 M({ id:'barrierhand', name:'Barrier Hand', tier:1, role:'shielded', fac:['HB','KV','AS'], mfr:'MM', blurb:'Carries a riot barrier. His shield absorbs damage until it breaks and leaves him staggered.', hp:42, speed:2.6, radius:.45, aggro:8, xp:18, dmg:1.2, melee:['swing'], moves:[], shield:.8, h:1.3, spr:'loader', pack:[2,3] }),
 M({ id:'sootwisp', name:'Soot Wisp', tier:1, role:'debuffer', fac:['HB','RC'], mfr:'HI', blurb:'A hovering ash-cloud with a hex-lamp. Its curse slows you and spikes your heat.', hp:22, speed:2.8, radius:.34, aggro:10, xp:14, dmg:1.0, melee:[], moves:[], custom:['hex'], ranged:true, keep:7, h:.85, hover:.55, spr:'drone', pack:[1,2] }),
 // ------------------------------------------------ TIER II
 M({ id:'menderwisp', name:'Mender Wisp', tier:2, role:'healer', fac:['AS','KV'], mfr:'PS', blurb:'A clinic repair-sprite. Beams health into the most wounded ally; kill it first.', hp:36, speed:2.9, radius:.34, aggro:10, xp:20, dmg:1.3, melee:['dart'], moves:[], custom:['mend'], ranged:true, keep:6, h:1.0, hover:.55, spr:'drone', pack:[1,2] }),
 M({ id:'longlens', name:'Long-Lens Marksman', tier:2, role:'sniper', fac:['AS','KV','RC'], mfr:'PS', blurb:'Stilt-legged rifle walker. Marks you with a long telegraph, then a heavy shot.', hp:40, speed:2.2, radius:.4, aggro:15, xp:24, dmg:1.35, melee:[], moves:[], custom:['snipe'], ranged:true, keep:10, h:1.9, spr:'shooter', pack:[1,2] }),
 M({ id:'handler', name:'Drone Handler', tier:2, role:'summoner', fac:['KV','AS'], mfr:'MM', blurb:'Carries a relay dish and releases inventory scanners to harass you.', hp:58, speed:2.4, radius:.42, aggro:10, xp:26, dmg:1.2, melee:['shot'], moves:[], custom:['summonlite'], summon:'scanner', ranged:true, keep:6, h:1.35, spr:'shiftlead', pack:[1,2] }),
 M({ id:'belltoller', name:'Bell Toller', tier:2, role:'caster', fac:['HB'], mfr:'HI', blurb:'Cast-bronze bell on his back. Every toll is a ring of shockwave you have to find the gap in.', hp:72, speed:2.3, radius:.45, aggro:9, xp:28, dmg:1.4, melee:['swing'], moves:[{k:'ring',p:{n:10,gaps:2,rad:4.2,r:1.3},w:1.0,cd:8,dmg:10},{k:'cross',p:{n:4,len:7,r:1.1},w:1.1,cd:10,dmg:10}], h:1.6, spr:'quenchpriest', pack:[1,2] }),
 M({ id:'bulwarktread', name:'Bulwark Tread', tier:2, role:'shielded', fac:['AS','KV','HB'], mfr:'PS', blurb:'A plated tracked guard with a deployable front shield. Slow, but nothing gets through it quickly.', hp:150, speed:1.9, radius:.6, aggro:8, xp:32, dmg:1.45, melee:['slam'], moves:[], shield:.7, h:1.1, spr:'gurneyrunner', pack:[1,2] }),
 M({ id:'sedabloom', name:'Sedative Bloom', tier:2, role:'debuffer', fac:['AS'], mfr:'PS', blurb:'A floating spore-bloom venting sedative gas and slowing hexes.', hp:44, speed:2.4, radius:.38, aggro:10, xp:24, dmg:1.35, melee:['gasvent'], moves:[], custom:['hex'], ranged:true, keep:7, h:1.05, hover:.55, spr:'drone', pack:[1,2] }),
 M({ id:'dustroach', name:'Dust Roach', tier:2, role:'swarmer', fac:['KV','RC'], mfr:'MM', blurb:'Warehouse vermin the size of a boot. Bites in close and spits a short acid fan.', hp:22, speed:4.4, radius:.34, aggro:8, xp:9, dmg:1.1, melee:['bite'], moves:[{k:'fan',p:{n:3,spread:40,speed:10},w:.6,cd:4.2,min:2,max:9,dmg:7}], h:.68, spr:'cinderhound', pack:[6,9] }),
 // ------------------------------------------------ TIER III
 M({ id:'shiftstalker', name:'Shift Stalker', tier:3, role:'charger', fac:['QS','AS'], mfr:'PS', blurb:'Night-shift assassin. Blinks to your back and strikes before you can turn.', hp:88, speed:3.7, radius:.42, aggro:6, xp:36, dmg:1.7, melee:['swing','blink'], moves:[], h:1.5, spr:'matron', pack:[1,3] }),
 M({ id:'mortartread', name:'Mortar Tread', tier:3, role:'caster', fac:['RC','KV','HB'], mfr:'HI', blurb:'Tracked mortar. Drops a salvo of slow, telegraphed shells around you from range.', hp:135, speed:1.8, radius:.62, aggro:13, xp:42, dmg:1.65, melee:[], moves:[{k:'marks',p:{n:4,r:1.5,spread:3},w:1.3,cd:6.5,min:4,max:16,dmg:13}], ranged:true, keep:9, h:1.05, spr:'slagcannon', pack:[1,2] }),
 M({ id:'leechorderly', name:'Leech Orderly', tier:3, role:'bruiser', fac:['AS'], mfr:'PS', blurb:'A ward orderly fitted with extraction needles. Heals from the damage it deals.', hp:112, speed:3.2, radius:.42, aggro:8, xp:38, dmg:1.7, melee:['swing','cleave'], moves:[], lifesteal:.6, h:1.45, spr:'orderly', pack:[2,3] }),
 M({ id:'packmule', name:'Pack Mule', tier:3, role:'exploder', fac:['KV','RC'], mfr:'MM', blurb:'A quadruped hauler strapped with live crates. Rushes in and goes off like a pallet of fireworks.', hp:96, speed:3.0, radius:.6, aggro:9, xp:42, dmg:1.7, melee:['swing'], moves:[], custom:['detonate_big'], h:1.25, spr:'forkbot', pack:[1,2] }),
 M({ id:'relaynode', name:'Relay Node', tier:3, role:'support', fac:['QS','RC','AS'], mfr:'MM', blurb:'A spiked relay core. Projects shields onto nearby allies. Break it to strip their cover.', hp:72, speed:2.4, radius:.36, aggro:10, xp:38, dmg:1.5, melee:['dart'], moves:[], custom:['ward'], ranged:true, keep:7, h:1.25, hover:.6, spr:'drone', pack:[1,1] }),
 M({ id:'rebarcrusher', name:'Rebar Crusher', tier:3, role:'charger', fac:['HB','RC'], mfr:'HI', blurb:'A slab-plated demolition beast. Wind-up charge that smashes through packs and floor alike.', hp:195, speed:3.2, radius:.7, aggro:9, xp:58, dmg:1.75, melee:['charge','slam','cleave'], moves:[], h:1.35, spr:'sawhand', pack:[1,1] }),
 M({ id:'staticpup', name:'Static Pup', tier:3, role:'swarmer', fac:['QS','RC'], mfr:'MM', blurb:'Cable-chewing mongrels charged with grid static. Fast, frail and always in a pack.', hp:28, speed:5.0, radius:.32, aggro:9, xp:12, dmg:1.5, melee:['bite'], moves:[], hasted:true, h:.58, spr:'cinderhound', pack:[8,12] }),
 // ------------------------------------------------ TIER IV
 M({ id:'recalltrooper', name:'Recall Trooper', tier:4, role:'shielded', fac:['RA'], mfr:'MM', blurb:'Authority line infantry with a deployable plate shield and a five-round fan carbine.', hp:155, speed:2.7, radius:.45, aggro:10, xp:56, dmg:1.9, melee:['shot'], moves:[{k:'fan',p:{n:5,spread:36,speed:12},w:.9,cd:3.4,min:3,max:12,dmg:11}], ranged:true, shield:.6, h:1.55, spr:'shooter', pack:[2,3] }),
 M({ id:'tagcarrier', name:'Tag Carrier', tier:4, role:'summoner', fac:['RA'], mfr:'MM', blurb:'Armoured carrier with a kennel rack. Releases tagged hounds in pairs.', hp:270, speed:1.9, radius:.7, aggro:10, xp:76, dmg:1.9, melee:['slam'], moves:[], custom:['summonlite'], summon:'staticpup', h:1.45, spr:'gurneyrunner', pack:[1,1] }),
 M({ id:'reclaimwalker', name:'Reclaim Walker', tier:4, role:'sniper', fac:['RA'], mfr:'MM', blurb:'Seven-foot sniper stilt. Long telegraph, heavy hit, and it keeps its distance.', hp:112, speed:2.3, radius:.42, aggro:16, xp:62, dmg:1.9, melee:[], moves:[], custom:['snipe'], ranged:true, keep:11, h:2.4, spr:'shooter', pack:[1,2] }),
 M({ id:'purgebeacon', name:'Purge Beacon', tier:4, role:'debuffer', fac:['RA'], mfr:'MM', blurb:'A seeing-eye drone. Hexes you, then calls down a ring of purge fire.', hp:125, speed:2.6, radius:.4, aggro:12, xp:60, dmg:1.9, melee:[], moves:[{k:'rain',p:{n:7,area:6,r:1.3},w:1.0,cd:8,min:0,max:15,dmg:11}], custom:['hex'], ranged:true, keep:8, h:1.45, hover:.6, spr:'drone', pack:[1,1] }),
 M({ id:'sweepertread', name:'Sweeper Mk II', tier:4, role:'shielded', fac:['RA'], mfr:'MM', blurb:'Heavy siege tread with a shield array. Salvos of shells and a closing ring of fire.', hp:340, speed:1.7, radius:.7, aggro:12, xp:84, dmg:1.95, melee:['slam'], moves:[{k:'marks',p:{n:5,r:1.6,spread:3.2},w:1.3,cd:6,min:4,max:17,dmg:13},{k:'ring',p:{n:12,gaps:2,rad:5.5,r:1.5},w:1.3,cd:11,dmg:11}], ranged:true, keep:7, shield:.7, h:1.6, spr:'gurneyrunner', pack:[1,1] }),
 M({ id:'repocrawler', name:'Repo Crawler', tier:4, role:'charger', fac:['RA'], mfr:'MM', blurb:'Armoured repossession crawler. Fast, bites hard and lunges in a long charge.', hp:125, speed:4.0, radius:.5, aggro:10, xp:54, dmg:1.9, melee:['bite','charge'], moves:[], hasted:true, h:1.05, spr:'cinderhound', pack:[2,3] }),
 M({ id:'triagewarden', name:'Triage Warden', tier:4, role:'healer', fac:['RA'], mfr:'PS', blurb:'Authority field medic. Heals and shields its squad, and will stab you if you come close.', hp:185, speed:2.8, radius:.45, aggro:10, xp:72, dmg:1.9, melee:['swing'], moves:[], custom:['mend','ward'], ranged:true, keep:6, h:1.75, spr:'matron', pack:[1,1] }),
];
export const MOB_BY_ID:Record<string,MobSpec>=Object.fromEntries(MOBS.map(m=>[m.id,m]));
export const MOB_IDS=MOBS.map(m=>m.id);
/** mob-only attacks (runtime in mobs.ts). base damage per attack, windup etc. */
export const MOB_ATK:Record<string,{w:number;rec:number;cd:number;min:number;max:number;lock?:boolean;ranged?:boolean}>={
  snipe:{w:1.5,rec:.9,cd:5.5,min:5,max:18,lock:true,ranged:true}, mend:{w:.8,rec:.5,cd:4.5,min:0,max:60}, ward:{w:.8,rec:.5,cd:7.5,min:0,max:60},
  hex:{w:.9,rec:.6,cd:6,min:2,max:13,lock:true,ranged:true}, detonate:{w:.9,rec:.1,cd:1,min:0,max:1.9}, detonate_big:{w:1.1,rec:.1,cd:1,min:0,max:2.4}, summonlite:{w:.9,rec:.8,cd:BAL.p.summonCd,min:0,max:40},
};
export const MOB_DMG:Record<string,number>={ snipe:BAL.p.snipe, mend:0, ward:0, hex:4, detonate:BAL.p.detonate, detonate_big:BAL.p.detonateBig, summonlite:0 };
export const MOB_META=(m:MobSpec):MobMeta=>({ tier:m.tier, role:m.role, fac:m.fac, lifesteal:m.lifesteal, shield:m.shield, keep:m.keep, hasted:m.hasted });
/** Elite affixes: availability escalates with tier (see TIER_CURVE.affixes for how many a pack leader rolls). */
export type Affix='hasted'|'volatile'|'shielded'|'regenerating'|'vampiric'|'frenzied'|'warded';
export const AFFIX_TIER:Record<Affix,number>={ hasted:1, volatile:1, shielded:2, regenerating:2, vampiric:3, frenzied:3, warded:4 };
export const AFFIX_LABEL:Record<Affix,string>={ hasted:'Hasted', volatile:'Volatile', shielded:'Shielded', regenerating:'Regenerating', vampiric:'Vampiric', frenzied:'Frenzied', warded:'Warded' };
export const AFFIX_DESC:Record<Affix,string>={ hasted:'+30% move speed, attacks faster', volatile:'explodes on death', shielded:'spawns with a 50% HP shield', regenerating:'regains 2.5% HP/s while out of combat damage', vampiric:'melee hits heal it', frenzied:'below 40% HP: +35% speed, +40% attack rate', warded:'immune to damage for 2s after dropping below 50% (once)' };
