// node tools/balance/compare.mjs before.json after.json  -> markdown tables for docs/BALANCE.md
import fs from 'fs';
const load = f => JSON.parse(fs.readFileSync(f, 'utf8')); const A = load(process.argv[2]), B = load(process.argv[3]); const meta = B.meta;
const PARKIT = d => ({ annex: 'mid', warehouse: 'mid', foundry: 'blue', clinic: 'purple' }[d.id] || { 1: 'mid', 2: 'blue', 3: 'purple', 4: 'purple' }[d.tier]);
const avg = a => a.length ? a.reduce((x, y) => x + y, 0) / a.length : NaN; const pct = x => isNaN(x) ? '-' : Math.round(x * 100) + '%'; const f = (x, d = 0) => isNaN(x) ? '-' : x.toFixed(d);
const lv = D => D.results.filter(x => x.r && x.job.mode === 'level' && !x.r.error).map(x => x.r); const mb = D => D.results.filter(x => x.r && x.job.mode === 'mob').map(x => x.r);
const stat = (rs, kit) => { const k = rs.filter(r => r.kit === kit); const cl = k.filter(r => r.cleared); return { n: k.length, clear: cl.length / k.length, deaths: avg(k.map(r => r.deaths)), t: avg(cl.map(r => r.t)), bt: avg(cl.map(r => r.bossTtk).filter(Boolean)) }; };
const la = lv(A), lb = lv(B);
console.log('### Par-kit results per level (before -> after)\n'); console.log('| level | tier | par kit | clear | deaths/run | time-to-clear (s) | boss TTK (s) |'); console.log('|---|---|---|---|---|---|---|');
for (const d of meta.dd) { const k = PARKIT(d); const a = stat(la.filter(r => r.id === d.id), k), b = stat(lb.filter(r => r.id === d.id), k); console.log(`| ${d.id} | ${d.tier || 'base'} | ${k} | ${pct(a.clear)} -> **${pct(b.clear)}** | ${f(a.deaths, 1)} -> ${f(b.deaths, 1)} | ${f(a.t)} -> ${f(b.t)} | ${f(a.bt)} -> ${f(b.bt)} |`); }
console.log('\n### Par-kit results per tier\n'); console.log('| tier | clear | deaths/run | time-to-clear (s) | boss TTK (s) |'); console.log('|---|---|---|---|---|');
for (const t of [0, 1, 2, 3, 4]) { const ds = meta.dd.filter(d => (d.tier || 0) === t); const g = L => { const rs = L.filter(r => ds.some(d => d.id === r.id && PARKIT(d) === r.kit)); const cl = rs.filter(r => r.cleared); return { clear: cl.length / rs.length, deaths: avg(rs.map(r => r.deaths)), t: avg(cl.map(r => r.t)), bt: avg(cl.map(r => r.bossTtk).filter(Boolean)) }; }; const a = g(la), b = g(lb); console.log(`| ${t || 'base'} | ${pct(a.clear)} -> **${pct(b.clear)}** | ${f(a.deaths, 2)} -> ${f(b.deaths, 2)} | ${f(a.t)} -> ${f(b.t)} | ${f(a.bt)} -> ${f(b.bt)} |`); }
console.log('\n### Clear rate by kit and tier (before -> after)\n'); const KITS = ['starter', 'mid', 'blue', 'purple', 'orange']; console.log('| tier | ' + KITS.join(' | ') + ' |'); console.log('|---|' + KITS.map(() => '---|').join(''));
for (const t of [0, 1, 2, 3, 4]) { const ids = meta.dd.filter(d => (d.tier || 0) === t).map(d => d.id); const cells = KITS.map(k => { const g = L => { const rs = L.filter(r => ids.includes(r.id) && r.kit === k); return rs.length ? rs.filter(r => r.cleared).length / rs.length : NaN; }; return pct(g(la)) + ' -> ' + pct(g(lb)); }); console.log(`| ${t || 'base'} | ${cells.join(' | ')} |`); }
console.log('\n### Damage taken by source, top 10 (mean HP per run across all kits, before -> after)\n'); console.log('| source | before | after |'); console.log('|---|---|---|');
const srcAvg = L => { const m = {}; for (const r of L) for (const [k, v] of Object.entries(r.src)) m[k] = (m[k] || 0) + v / L.length; return m; }; const sa = srcAvg(la), sb = srcAvg(lb); for (const [k] of Object.entries(sa).sort((a, b) => b[1] - a[1]).slice(0, 10)) console.log(`| ${k} | ${f(sa[k], 1)} | ${f(sb[k] || 0, 1)} |`);
console.log('\n### Mob duels: 3 of a kind vs the par kit for their tier (before -> after)\n'); console.log('| mob | tier/role | kill time (s) | HP lost per fight | max single hit | timeouts (60 s) |'); console.log('|---|---|---|---|---|---|');
const ma = mb(A), mbb = mb(B); for (const m of meta.mobs) { const g = L => { const q = L.filter(r => r.id === m.id && (r.par ?? true)); return { t: avg(q.map(r => r.t)), hp: avg(q.map(r => Object.values(r.src).reduce((a, b) => a + b, 0))), mh: q.length ? Math.max(...q.map(r => r.maxHit)) : NaN, to: q.filter(r => r.t >= 59).length, n: q.length }; }; const a = g(ma), b = g(mbb); console.log(`| ${m.id} | T${m.tier} ${m.role} | ${f(a.t)} -> ${f(b.t)} | ${f(a.hp)} -> ${f(b.hp)} | ${f(a.mh)} -> ${f(b.mh)} | ${a.to}/${a.n} -> ${b.to}/${b.n} |`); }
console.log('\n### Ability usage per run (mean casts, par kit, after)\n'); const ab = {}; for (const r of lb) if (r.kit === PARKIT(meta.dd.find(d => d.id === r.id))) for (const [k, v] of Object.entries(r.abil)) (ab[k] ||= []).push(v); const par = lb.filter(r => r.kit === PARKIT(meta.dd.find(d => d.id === r.id))).length; console.log(Object.entries(ab).map(([k, v]) => `${k} ${f(v.reduce((a, b) => a + b, 0) / par, 1)}`).join(', '));
