// node tools/balance/report.mjs <results.json> [--md]  -> per-level and per-mob tables + outlier list
import fs from 'fs';
const f = process.argv[2]; const { meta, results } = JSON.parse(fs.readFileSync(f, 'utf8')); const MD = process.argv.includes('--md');
const KITS = ['starter', 'mid', 'blue', 'purple', 'orange']; const avg = a => a.length ? a.reduce((x, y) => x + y, 0) / a.length : NaN; const pct = x => isNaN(x) ? '-' : Math.round(x * 100) + '%'; const fx = (x, d = 0) => isNaN(x) ? '-' : x.toFixed(d);
const lv = results.filter(x => x.r && x.job.mode === 'level' && !x.r.error).map(x => x.r); const mb = results.filter(x => x.r && x.job.mode === 'mob').map(x => x.r);
const by = (arr, k) => { const m = {}; for (const r of arr) (m[k(r)] ||= []).push(r); return m; };
export function levelStats(lv) { const out = {}; for (const [id, rs] of Object.entries(by(lv, r => r.id))) { out[id] = {}; for (const kit of KITS) { const k = rs.filter(r => r.kit === kit); if (!k.length) continue; const cl = k.filter(r => r.cleared); out[id][kit] = { n: k.length, clear: cl.length / k.length, deaths: avg(k.map(r => r.deaths)), t: avg(cl.map(r => r.t)), bossTtk: avg(cl.map(r => r.bossTtk).filter(x => x)), maxHit: Math.max(...k.map(r => r.maxHit)), hp: k[0].maxHp, why: k.filter(r => !r.cleared).map(r => r.failWhy).join(',') }; } } return out; }
const LS = levelStats(lv); const tier = id => (meta.dd.find(d => d.id === id) || {}).tier || 0;
const PARKIT = d => ({ annex: 'mid', warehouse: 'mid', foundry: 'blue', clinic: 'purple' }[d.id] || { 1: 'mid', 2: 'blue', 3: 'purple', 4: 'purple' }[d.tier]);
const APPROP = { 1: ['starter', 'mid'], 2: ['mid'], 3: ['purple'], 4: ['purple', 'orange'], 0: ['mid'] };
console.log((MD ? '| ' : '') + ['level', 'tier', 'lvl', ...KITS.map(k => k + ' clear/deaths/time')].join(MD ? ' | ' : '\t') + (MD ? ' |' : ''));
if (MD) console.log('|' + '---|'.repeat(3 + KITS.length));
for (const d of meta.dd) { const s = LS[d.id]; if (!s) continue; const cells = KITS.map(k => s[k] ? `${pct(s[k].clear)}/${fx(s[k].deaths, 1)}/${fx(s[k].t)}s` : '-'); console.log((MD ? '| ' : '') + [d.id, d.tier || 'base', Math.round((d.min + d.max) / 2), ...cells].join(MD ? ' | ' : '\t') + (MD ? ' |' : '')); }
console.log('\nTier summary (appropriate kits: T1 starter+mid... see APPROP):');
for (const t of [0, 1, 2, 3, 4]) { const ids = meta.dd.filter(d => (d.tier || 0) === t).map(d => d.id); for (const kit of KITS) { const rs = lv.filter(r => ids.includes(r.id) && r.kit === kit); if (!rs.length) continue; console.log(`tier ${t || 'base'} ${kit}: clear ${pct(rs.filter(r => r.cleared).length / rs.length)} deaths ${fx(avg(rs.map(r => r.deaths)), 2)} time ${fx(avg(rs.filter(r => r.cleared).map(r => r.t)))}s bossTTK ${fx(avg(rs.filter(r => r.cleared && r.bossTtk).map(r => r.bossTtk)), 1)}s`); } }
console.log('\nDamage taken by source (mean per run, top 12 across all runs):'); { const m = {}; for (const r of lv) for (const [k, v] of Object.entries(r.src)) { (m[k] ||= []).push(v); } const rows = Object.entries(m).map(([k, v]) => [k, v.reduce((a, b) => a + b, 0) / lv.length]).sort((a, b) => b[1] - a[1]).slice(0, 12); for (const [k, v] of rows) console.log('  ' + k.padEnd(28) + fx(v, 1)); }
console.log('\nPAR kit clear rate per level (par: annex/warehouse mid, foundry blue, clinic purple, T1 mid, T2 blue, T3 purple, T4 purple):'); for (const d of meta.dd) { const s = LS[d.id]?.[PARKIT(d)]; if (s) console.log('  ' + d.id.padEnd(18) + 'T' + (d.tier || 0) + ' ' + PARKIT(d).padEnd(7) + pct(s.clear).padEnd(6) + 'deaths ' + fx(s.deaths, 1) + ' time ' + fx(s.t) + 's bossTTK ' + fx(s.bossTtk) + 's'); }
for (const t of [0, 1, 2, 3, 4]) { const ds = meta.dd.filter(d => (d.tier || 0) === t); const rs = lv.filter(r => ds.some(d => d.id === r.id && PARKIT(d) === r.kit)); if (rs.length) console.log(`  PAR tier ${t || 'base'}: clear ${pct(rs.filter(r => r.cleared).length / rs.length)} deaths ${fx(avg(rs.map(r => r.deaths)), 2)} time ${fx(avg(rs.filter(r => r.cleared).map(r => r.t)))}s`); }
console.log('\nBoss TTK (s, orange/purple/mid/starter kits, cleared runs) and boss damage share:');
for (const d of meta.dd) { const rs = lv.filter(r => r.id === d.id); const row = KITS.map(k => { const c = rs.filter(r => r.kit === k && r.cleared && r.bossTtk); return c.length ? fx(avg(c.map(r => r.bossTtk)), 0) : '-'; }); console.log('  ' + d.id.padEnd(18) + d.boss.padEnd(16) + row.join('\t')); }
console.log('\nMob duel (3 of a kind vs par kit for their tier; "down" = one kit below): TTK s / HP lost per fight / downed, maxHit, timeouts(60s)');
{ const m = by(mb, r => r.id); for (const mo of meta.mobs) { const rs = m[mo.id] || []; const cell = par => { const q = rs.filter(r => (r.par ?? true) === par); if (!q.length) return '-'; const dmgT = avg(q.map(r => Object.values(r.src).reduce((a, b) => a + b, 0))); return `${fx(avg(q.map(r => r.t)), 0)}s/${fx(dmgT, 0)}hp/${q.filter(r => r.downed).length}dn/${q.filter(r => r.t >= 59).length}to`; }; const q = rs.filter(r => r.par); const mh = q.length ? Math.max(...q.map(r => r.maxHit)) : 0; const hp = q[0]?.kitInfo?.hp; console.log('  ' + mo.id.padEnd(15) + ('T' + mo.tier + ' ' + mo.role).padEnd(14) + 'par ' + cell(true).padEnd(20) + 'down ' + cell(false).padEnd(20) + `maxHit ${fx(mh)}/${hp || '?'}hp (${q.find(r => r.maxHit === mh)?.maxHitSrc || ''})`); } }
export { LS };
